name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.3"

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Run DVC
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          dvc repro

      - name: Stage Model
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python3 src/models/model_stage.py

      - name: Test Model
        env: 
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python3 tests/test_model.py
